version: "3.8"
services:
  NodeChat:
    image: b0ltz205/nodechat:lts
    build: .
    container_name: SecureChatNew
    ports:
      - "80:3700"
    environment:
      - PORT=3700
    volumes:
      - ./:/app
